services:
  solr:
    build:
      context: solr/
    ports:
      - 8983:8983
    environment:
      SOLR_OPTS: "-Dsolr.config.lib.enabled=true"
    command:
      - solr-precreate
      - plone
      - /plone-config
