# syntax=docker/dockerfile:1
FROM solr:8

LABEL maintainer="kitconcept, GmbH <info@kitconcept.com>" \
      org.label-schema.name="kitconcept-internet-solr" \
      org.label-schema.description="KitConcept Solr installation" \
      org.label-schema.vendor="kitconcept, GmbH"

COPY etc /plone-config
