name: "Compute values used in workflow"

on:
  workflow_call:
    inputs:
      image-name-prefix:
        required: false
        type: string
        default: "ghcr.io/kitconcept/kitconcept-solr"
      node-version:
        required: false
        type: string
        default: "22.x"
      python-version:
        required: false
        type: string
        default: "3.12"
    outputs:
      acceptance:
        description: "Flag reporting if we should run the acceptance jobs"
        value: ${{ jobs.config.outputs.acceptance }}
      backend:
        description: "Flag reporting if we should run the backend jobs"
        value: ${{ jobs.config.outputs.backend }}
      docs:
        description: "Flag reporting if we should run the docs jobs"
        value: ${{ jobs.config.outputs.docs }}
      frontend:
        description: "Flag reporting if we should run the frontend jobs"
        value: ${{ jobs.config.outputs.frontend }}
      solr:
        description: "Flag reporting if we should run the solr jobs"
        value: ${{ jobs.config.outputs.solr }}
      base-tag:
        description: "Base tag to be used when creating container images"
        value: ${{ jobs.config.outputs.base-tag }}
      image-name-prefix:
        description: "Image name prefix for container images"
        value: ${{ inputs.image-name-prefix }}
      node-version:
        description: "Node version to be used"
        value: ${{ inputs.node-version }}
      python-version:
        description: "Python version to be used"
        value: ${{ inputs.python-version }}
      plone-version:
        description: "Plone version to be used"
        value: ${{ jobs.config.outputs.plone-version }}
      volto-version:
        description: "Volto version to be used"
        value: ${{ jobs.config.outputs.volto-version }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      acceptance: ${{ steps.filter.outputs.acceptance }}
      backend: ${{ steps.filter.outputs.backend }}
      devops: ${{ steps.filter.outputs.devops }}
      docs: ${{ steps.filter.outputs.docs }}
      frontend: ${{ steps.filter.outputs.frontend }}
      solr: ${{ steps.filter.outputs.solr }}
      base-tag: ${{ steps.vars.outputs.BASE_TAG }}
      plone-version: ${{ steps.vars.outputs.PLONE_VERSION }}
      volto-version: ${{ steps.vars.outputs.VOLTO_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute several vars needed for the CI
        id: vars
        run: |
          echo "BASE_TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "PLONE_VERSION=$(cat backend/version.txt)" >> $GITHUB_OUTPUT
          python3 -c 'import json; data = json.load(open("./frontend/mrs.developer.json")); print("VOLTO_VERSION=" + (data["core"].get("tag") or "latest"))' >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            acceptance:
              - '.github/workflows/acceptance*'
              - '.github/workflows/backend*'
              - '.github/workflows/frontend*'
              - 'backend/**'
              - 'frontend/**'
            backend:
              - 'backend/**'
              - '.github/workflows/backend*'
            devops:
              - 'devops/**'
            docs:
              - '.readthedocs.yaml'
              - 'docs/**'
              - '.github/workflows/docs.yaml'
            frontend:
              - 'frontend/**'
              - '.github/workflows/frontend*'
            solr:
              - 'solr/**'
              - '.github/workflows/solr*'

      - name: Test vars
        run: |
          echo "BASE_TAG: ${{ steps.vars.outputs.BASE_TAG }}"
          echo 'PLONE_VERSION: ${{ steps.vars.outputs.PLONE_VERSION }}'
          echo 'VOLTO_VERSION: ${{ steps.vars.outputs.VOLTO_VERSION }}'
          echo 'event-name: ${{ github.event_name }}'
          echo 'Paths - acceptance: ${{ steps.filter.outputs.acceptance }}'
          echo 'Paths - backend: ${{ steps.filter.outputs.backend }}'
          echo 'Paths - docs: ${{ steps.filter.outputs.docs }}'
          echo 'Paths - frontend: ${{ steps.filter.outputs.frontend }}'
          echo 'Paths - solr: ${{ steps.filter.outputs.solr }}'